# Generated by Django 4.2.6 on 2023-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='Address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='City',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='Country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
