# Generated by Django 4.2.6 on 2023-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentaccount_address_studentaccount_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
