# Generated by Django 4.2.6 on 2023-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('credit', models.IntegerField(choices=[(20, 20), (40, 40), (60, 60)])),
                ('catagory', models.CharField(choices=[('In-person', 'In person'), ('Online', 'Online')], max_length=20)),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
