# Generated by Django 4.2.6 on 2023-12-05 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=20, primary_key='name', serialize=False)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.CharField(choices=[('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=4, primary_key='code', serialize=False)),
                ('credit', models.IntegerField(choices=[(20, 20), (40, 40), (60, 60)])),
                ('category', models.CharField(choices=[('In-person', 'In person'), ('Online', 'Online')], max_length=20)),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('coursesAllowedToRegister', models.ManyToManyField(to='ModuleRegistrationSystem.course')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfRegistration', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduleregistrations', to='ModuleRegistrationSystem.module')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentregistrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
