# Generated by Django 4.2.6 on 2023-11-23 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ModuleRegistrationSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
                ('courseStartDate', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.CharField(choices=[('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years')], max_length=10)),
                ('courseDescription', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduleregistrations', to='ModuleRegistrationSystem.module'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentregistrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseModules', to='ModuleRegistrationSystem.course')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduleCourses', to='ModuleRegistrationSystem.module')),
            ],
        ),
    ]
