# Generated by Django 4.2.6 on 2023-11-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='catagory',
            new_name='category',
        ),
    ]
