# Generated by Django 4.2.6 on 2023-11-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0002_course_alter_registration_module_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseModules',
            new_name='CourseModule',
        ),
    ]
