# Generated by Django 4.2.6 on 2023-11-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0002_rename_catagory_module_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=4, primary_key='code', serialize=False),
        ),
    ]
