# Generated by Django 4.2.6 on 2023-12-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0002_alter_registration_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='coursesAllowedToRegister',
            new_name='courses_Allowed_To_Register',
        ),
    ]
