# Generated by Django 4.2.6 on 2023-12-17 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0003_rename_coursesallowedtoregister_module_courses_allowed_to_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dateOfRegistration',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Picture', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('Module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModuleRegistrationSystem.module')),
            ],
        ),
    ]
