# Generated by Django 4.2.6 on 2023-11-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0003_rename_coursemodules_coursemodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseStartDate',
            new_name='startDate',
        ),
    ]
