# Generated by Django 4.2.6 on 2023-11-23 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ModuleRegistrationSystem', '0004_rename_coursedescription_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseStudent', to='ModuleRegistrationSystem.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentCourse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
