# Generated by Django 4.2.6 on 2023-11-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0005_coursestudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='CourseModule',
        ),
        migrations.DeleteModel(
            name='courseStudent',
        ),
    ]
