# Generated by Django 4.2.6 on 2023-11-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0006_remove_coursestudent_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='coursesAllowedToRegister',
            field=models.ManyToManyField(to='ModuleRegistrationSystem.course'),
        ),
    ]
