# Generated by Django 4.2.6 on 2023-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRegistrationSystem', '0007_module_coursesallowedtoregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
